### ISSUE TITLE
The build for FireFox does not work correctly

### ISSUE THREAD

**Issue by dejurin** [Qit-tools/browser-extension-password-generator-pro#1]
The build for FireFox does not work correctly. Popup does not start.

**Comment by dejurin** [comment]
```css
body {
    display: flex;
    flex-direction: column;
    width: 384px;
    min-height: 600px;
    overflow: hidden;
}
#app {
    flex: 1;
}
```
